name: filerain-dev

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: filerain
    ports:
      - "5432:5432"

  mail:
    image: dockage/mailcatcher:0.9.0
    ports:
      - 1080:1080
      - 1025:1025